### ISSUE TITLE
!!! tip not tipping

### ISSUE THREAD

**Issue by chrsmj** [asterisk/documentation#116] opened 2024-10-18 18:29 UTC
Occasionally there are some Tips like:

`!!! tip `

...that maybe were a callout or tooltip or box with a border ?

See 3rd paragraph at: https://docs.asterisk.org/Getting-Started/Installing-Asterisk/Installing-Asterisk-From-Source/What-to-Download/#asterisk

And a bit below that in the bottom of the DAHDI section: https://docs.asterisk.org/Getting-Started/Installing-Asterisk/Installing-Asterisk-From-Source/What-to-Download/#dahdi

**Comment by seanbright** [comment] 2024-10-18 19:06
Dupe of #79

**Closed by seanbright** 2024-10-18 19:06 UTC

**Comment by gtjoseph** [comment] 2024-10-18 21:03
Yeah I have a sticky note to convert all of the `!!!` admonitions to the new `///` style because the new style uses a closing `///` which makes it easier to put other things like code inside the admonition.

**Comment by seanbright** [comment] 2024-10-18 21:27
Can you link that documentation?

**Comment by gtjoseph** [comment] 2024-10-19 14:53
https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/

I'm going to update the README right now.

**Comment by gtjoseph** [comment] 2024-10-19 15:04
I also have adding a style guide on my list but I never seem to find the time.

**Comment by gtjoseph** [comment] 2024-10-19 15:29
[README.md](https://github.com/asterisk/documentation/blob/main/README.md) updated.
